from sklearn.metrics import (
    confusion_matrix,
    accuracy_score,
    precision_score,
    recall_score,
    f1_score,
    fbeta_score,
)
import numpy as np
import pandas as pd

from ds_package_classifier.base import BaseClassifier


def calculate_metrics(y_true: list[int], y_pred: list[int], average: str = "binary"):
    """
    Calculate evaluation metrics used to asses the performance of a classifier

    __PARAMETERS__
    y_true: list[int]
        The true target labels for the classification task.
    y_pred: list[int]
        The predicted labels generated by the classifier.
    average: str
        The averaging method used for precision, recall, and F1 score. Options include 'binary', 'macro', 'micro', 'weighted'. Default is 'binary'.

    __RETURNS__
    tuple: A tuple containing:
        - float: Accuracy of predictions
        - float: Precision of predictions
        - float: Recall of predictions
        - float: F1 score
        - ndarray: Confusion matrix
    """
    # Calculate evaluation metrics
    accuracy = accuracy_score(y_true, y_pred)
    precision = precision_score(y_true, y_pred, average=average)
    recall = recall_score(y_true, y_pred, average=average)
    f1 = f1_score(y_true, y_pred, average=average)

    # Calculate confusion matrix
    conf_matrix = confusion_matrix(y_true, y_pred)

    return accuracy, precision, recall, f1, conf_matrix


def get_cross_val_prediction_metrics(
    classifier: BaseClassifier, y: list[int], n_splits: int = 5, average: str = "binary"
):
    """
    Calculate evaluation metrics using cross-validated predictions from a classifier

    __PARAMETERS__
    classifier: BaseClassifier
        A classifier object that inherits from the BaseClassifier class and implements cross_val_predict.
    X: pd.DataFrame
        The input features used for training and prediction.
    y: list[int]
        The true target labels corresponding to the input features.
    n_splitss: int
        The number of folds to use for cross-validation. Default is 5.
    average: str
        The averaging method for precision, recall, and F1 score. Options include 'binary', 'macro', 'micro', 'weighted'. Default is 'binary'.

    __RETURNS__
    tuple: A tuple containing:
        - float: Accuracy of predictions
        - float: Precision of predictions
        - float: Recall of predictions
        - float: F1 score
        - ndarray: Confusion matrix
        - ndarray: List of predictions from cross_val_predict
    """

    # Get cross-validated predictions using StratifiedKFold
    y_pred_cross_val = classifier.cross_val_predict(n_splits)

    # Calculate evaluation metrics from predictions
    accuracy, precision, recall, f1, conf_matrix = calculate_metrics(
        y, y_pred_cross_val, average=average
    )

    return accuracy, precision, recall, f1, conf_matrix, y_pred_cross_val


def get_top_binary_thresholds(
    classifier: BaseClassifier,
    beta_values: list[int] = [],
    n_splits: int = 5,
):
    """
    Evaluates F1 and F-beta scores across a range of probability thresholds
    using cross-validation prediction for binary classification. Returns the best thresholds for each score.

    __PARAMETERS__
    classifier: BaseClassifier
        An instance of BaseClassifier containing the model, features, and labels.
    beta_values: list[int]
        List of beta values to evaluate (e.g., [2, 3, 5]).
    n_splits: int
        Number of folds for cross-validation.

    __RETURNS__
    best_thresholds: Dictionary mapping 'f1' and each 'fbeta_{beta}' to the threshold that yields its highest score.
    """

    # Get true target values
    y_true = classifier.y

    # Ensure binary classification
    unique_classes = np.unique(y_true)
    if len(unique_classes) != 2:
        raise ValueError(
            f"Binary classification expected, but found {len(unique_classes)} unique classes: {unique_classes}"
        )

    # Get probability predictions
    y_pred_cross_val_proba = classifier.cross_val_predict_proba(n_splits=n_splits)[:, 1]
    thresholds = np.linspace(0, 1, 100)

    # Initialise lists to store scores
    f1s = []
    fbeta_scores = {beta: [] for beta in beta_values}

    # Evaluate scores across thresholds
    for threshold in thresholds:
        y_pred = (y_pred_cross_val_proba >= threshold).astype(int)
        f1s.append(f1_score(y_true, y_pred, zero_division=0))
        for beta in beta_values:
            fbeta_scores[beta].append(
                fbeta_score(y_true, y_pred, beta=beta, zero_division=0)
            )

    # Select best thresholds
    best_thresholds = {"f1": thresholds[np.argmax(f1s)]}
    for beta in beta_values:
        best_thresholds[f"fbeta_{beta}"] = thresholds[np.argmax(fbeta_scores[beta])]

    return best_thresholds


def get_binary_thresholds_cross_val_prediction_metrics(
    classifier: BaseClassifier, thresholds: list[float], n_splits: int = 5
):
    """
    Calculates classification metrics (accuracy, precision, recall, F1) across a range of probability thresholds
    using cross-validation predictions for binary classification.

    __PARAMETERS__
    classifier: BaseClassifier
        An instance of BaseClassifier containing the model, features, and labels.
    thresholds: list[float]
        A list of float values representing decision thresholds to evaluate.
    n_splits: int
        Number of folds for StratifiedKFold cross-validation.

    __RETURNS__:
    df_threshold_metrics: A pandas DataFrame containing the evaluated metrics for each threshold.
        Columns include: 'threshold', 'accuracy', 'precision', 'recall', and 'f1'.
    """

    y_true = classifier.y

    # Ensure binary classification
    unique_classes = np.unique(y_true)
    if len(unique_classes) != 2:
        raise ValueError(
            f"Binary classification expected, but found {len(unique_classes)} unique classes: {unique_classes}"
        )

    y_pred_cross_val_proba = classifier.cross_val_predict_proba(n_splits=n_splits)[:, 1]

    accuracies = []
    precisions = []
    recalls = []
    f1s = []

    for threshold in thresholds:

        # Apply threshold to get binary predictions
        y_pred = (y_pred_cross_val_proba >= threshold).astype(int)

        # Calculate metrics for threshold predictions
        accuracy, precision, recall, f1, _ = calculate_metrics(y_true, y_pred)
        accuracies.append(accuracy)
        precisions.append(precision)
        recalls.append(recall)
        f1s.append(f1)

    # Build pd.DataFrame of results
    df_threshold_metrics = pd.DataFrame(
        {
            "threshold": thresholds,
            "accuracy": accuracies,
            "precision": precisions,
            "recall": recalls,
            "f1": f1s,
        }
    )

    return df_threshold_metrics
